<?php
declare(strict_types=1);

namespace Lafka\Tests\Unit;

use PHPUnit\Framework\TestCase;

/**
 * NX1-10b/c packaging contract: the minify dist step, its git-ignore, its lint
 * exclusions, and its release-workflow wiring must stay in place.
 *
 * The `.min` siblings are build artefacts: generated by `npm run build`
 * (scripts/build-assets.mjs), served at runtime by incl/system/asset-min.php,
 * never committed, and regenerated in release.yml before the zip. If any strand
 * of that contract is dropped — the build script deleted, the git-ignore
 * removed (artefacts leak into commits), a lint exclusion lost (generated files
 * break CI), or the release step un-wired (production ships un-minified) — this
 * test fails. It scans project files as text rather than executing Node.
 */
final class AssetBuildPipelineTest extends TestCase {

	private static function root(): string {
		return dirname( __DIR__, 2 );
	}

	private static function read( string $relative ): string {
		return (string) file_get_contents( self::root() . '/' . $relative );
	}

	public function test_build_script_exists_and_minifies_with_esbuild(): void {
		$this->assertFileExists( self::root() . '/scripts/build-assets.mjs' );
		$src = self::read( 'scripts/build-assets.mjs' );
		$this->assertStringContainsString(
			"from 'esbuild'",
			$src,
			'build-assets.mjs must use esbuild.'
		);
		$this->assertStringContainsString(
			'minify: true',
			$src,
			'build-assets.mjs must run esbuild in minify mode.'
		);
	}

	public function test_package_json_wires_build_and_esbuild_devdep(): void {
		$pkg = json_decode( self::read( 'package.json' ), true );
		$this->assertIsArray( $pkg );
		$this->assertSame(
			'node scripts/build-assets.mjs',
			$pkg['scripts']['build'] ?? null,
			'package.json must expose `npm run build` -> build-assets.mjs.'
		);
		$this->assertArrayHasKey(
			'esbuild',
			$pkg['devDependencies'] ?? array(),
			'esbuild must be a devDependency.'
		);
	}

	public function test_gitignore_excludes_generated_min_artifacts(): void {
		$ignore = self::read( '.gitignore' );
		$this->assertStringContainsString(
			'/styles/*.min.css',
			$ignore,
			'.gitignore must exclude generated styles/*.min.css.'
		);
		$this->assertStringContainsString(
			'/js/*.min.js',
			$ignore,
			'.gitignore must exclude generated js/*.min.js.'
		);
	}

	public function test_lint_configs_ignore_generated_min_files(): void {
		$this->assertStringContainsString(
			'**/*.min.js',
			self::read( 'eslint.config.mjs' ),
			'eslint must ignore generated *.min.js so the build never fails CI.'
		);
		$this->assertStringContainsString(
			'**/*.min.css',
			self::read( '.stylelintrc.json' ),
			'stylelint must ignore generated *.min.css so the build never fails CI.'
		);
	}

	public function test_release_workflow_builds_before_zipping(): void {
		$release = self::read( '.github/workflows/release.yml' );
		$this->assertStringContainsString(
			'actions/setup-node',
			$release,
			'release.yml must set up Node to run the build.'
		);
		$this->assertStringContainsString(
			'npm run build',
			$release,
			'release.yml must run `npm run build` to generate the .min assets.'
		);

		// The build must precede the zip so the fresh .min files are packaged.
		$build_pos = strpos( $release, 'npm run build' );
		$zip_pos   = strpos( $release, 'zip -r' );
		$this->assertNotFalse( $build_pos );
		$this->assertNotFalse( $zip_pos );
		$this->assertLessThan(
			$zip_pos,
			$build_pos,
			'The build step must run before the zip step.'
		);
	}
}
